Repository pathacks/codeschool-todolist, pull requests merged in 2020-10, with the labels that each got.

#2 Issue #1: add main files
  index.html
  styles.css
Labels: hacktoberfest-accepted

#4 Issue #2: Week one homework
  week-one/week-one.html
Labels: hacktoberfest-accepted

#9 Issue #7 - Week 4 Homework
  week-four/week-four.html
Labels: good first issue, hacktoberfest-accepted, homework

#13 Issue #12 - Week Six Homewoork
  week-six/week-six-homework.html
Labels: hacktoberfest-accepted, homework

#14 Add files via upload
  week1homework.html
Labels: hacktoberfest-accepted, homework

#19 Add Week 3 HW Folder
  week-three/Week3HW.html
Labels: hacktoberfest-accepted

#20 Add Week 5 HW & Folder
  week-five/Week5HW.html
  week-one/Week1HW - Loi.html
  week-two/Week2HW - Loi.html
Labels: hacktoberfest-accepted

#22 Add Week 4 HW - Loi to Week 4 Folder
  week-four/Week4HW - Loi.html
Labels: hacktoberfest-accepted, homework
